export enum SocialTypesEnum {
  Email = 'email',
  WebSite = 'website',
  Linkedin = 'linkedin',
  Facebook = 'facebook',
  Twitter = 'twitter',
  Github = 'github',
  Behance = 'behance',
  DevTo = 'dev_to',
  Dribbble = 'dribbble',
  Exercism = 'exercism',
  Instagram = 'instagram',
  Keybase = 'keybase',
  Medium = 'medium',
  Patreon = 'patreon',
  Stackoverflow = 'stackoverflow',
  Substack = 'substack',
  Telegram = 'telegram',
  Tiktok = 'tiktok',
  Twitch = 'twitch',
  Vk = 'vk',
  Youtube = 'youtube',
}
